### ISSUE TITLE
AttributeError: 'list' object has no attribute 'get'

### ISSUE THREAD

**Issue by supersri811** [DemonKingSwarn/flix-cli#16]
**Metadata (please complete the following information)**
Version: 1.5.3
OS: Manjaro 22.1
Movie: Every
**Describe the bug**
Stops every time displaying this error:
`
Traceback (most recent call last):
  File "/home/user/.local/bin/flix-cli", line 5, in <module>
    from flix_cli.__main__ import __flixcli__
  File "/home/user/.local/lib/python3.10/site-packages/flix_cli/__main__.py", line 1, in <module>
    from .core import __flix_cli__
  File "/home/user/.local/lib/python3.10/site-packages/flix_cli/core/__flix_cli__.py", line 219, in <module>
    poison()
  File "/home/user/.local/lib/python3.10/site-packages/flix_cli/core/__flix_cli__.py", line 213, in poison
    movie()
  File "/home/user/.local/lib/python3.10/site-packages/flix_cli/core/__flix_cli__.py", line 94, in movie
    movie.subtitles = (_.get("file") for _ in content.get("track", {}).get("tracks", []))
AttributeError: 'list' object has no attribute 'get'
`

**Steps To Reproduce**

1. Run `flix-cli <any movie/series>`
2. Choose an option

**Expected behavior**
Downloading should work

**Screenshots (if applicable; you can just drag the image onto github)**

**Additional context**

**Comment by DemonKingSwarn** [comment]
Did you try `pip install flix-cli --upgrade` as the version you are using is the old one.
