### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by dillfrescott** [DemonKingSwarn/flix-cli#17]
```
Enter season: 1
Enter episode: 1
Traceback (most recent call last):
  File "C:\Users\micro\miniconda3\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\micro\miniconda3\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\micro\miniconda3\Scripts\flix-cli.exe\__main__.py", line 4, in <module>
  File "C:\Users\micro\miniconda3\lib\site-packages\flix_cli\__main__.py", line 1, in <module>
    from .core import __flix_cli__
  File "C:\Users\micro\miniconda3\lib\site-packages\flix_cli\core\__flix_cli__.py", line 219, in <module>
    poison()
  File "C:\Users\micro\miniconda3\lib\site-packages\flix_cli\core\__flix_cli__.py", line 215, in poison
    series()
  File "C:\Users\micro\miniconda3\lib\site-packages\flix_cli\core\__flix_cli__.py", line 131, in series
    ).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by HPMED1** [comment]
no support gg

**Comment by DemonKingSwarn** [comment]
sorry, i am currently busy with uni stuffs. will fix it soon

**Comment by ameeralbeladi965-dev** [comment]
its 2025 and still didn't fixed, get back to work
