### ISSUE TITLE
`flix-cli` does not seem to work, manjaro.

### ISSUE THREAD

**Issue by hajonnes** [DemonKingSwarn/flix-cli#18]
**Metadata (please complete the following information)**  
Version: 1.6.2  
OS: 6.5.5-1-MANJARO  
Python 3.11.5  
Installed with `pipx install flix-cli`  

Movie: chobits s1 e1   

**Describe the bug**
The program only generate what seems like errors
```
 $flix-cli Chobits  
                                                                                                                                                         
 Enter season: 1
 Enter episode: 1
 Traceback (most recent call last):
File "/home/rxt/.local/bin/flix-cli", line 5, in <module>
from flix_cli.__main__ import __flixcli__
File "/home/rxt/.local/pipx/venvs/flix-cli/lib/python3.11/site-packages/flix_cli/__main__.py", line 1, in <module>
from .core import __flix_cli__
File "/home/rxt/.local/pipx/venvs/flix-cli/lib/python3.11/site-packages/flix_cli/core/__flix_cli__.py", line 219, in <module>
poison()
File "/home/rxt/.local/pipx/venvs/flix-cli/lib/python3.11/site-packages/flix_cli/core/__flix_cli__.py", line 215, in poison
series()
File "/home/rxt/.local/pipx/venvs/flix-cli/lib/python3.11/site-packages/flix_cli/core/__flix_cli__.py", line 135, in series
json.loads(
File "/usr/lib/python3.11/json/__init__.py", line 346, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/json/decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/json/decoder.py", line 355, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```
**Steps To Reproduce**

1. install flix-cli with `pipx install flix-cli`
2. choose Chobits s1 e1  

**Expected behavior**  
Downloading should work

**Comment by DemonKingSwarn** [comment]
i am working on its new update, will also add an auto fix functionality this time

**Comment by ASSahasranamam** [comment]
Garuda Linux user here: 

Having similar issues


`Traceback (most recent call last):
File "/home/maltesefalcon/anaconda3/bin/flix-cli", line 5, in <module>
from flix_cli.__main__ import __flixcli__
File "/home/maltesefalcon/anaconda3/lib/python3.9/site-packages/flix_cli/__main__.py", line 1, in <module>
from .core import __flix_cli__
File "/home/maltesefalcon/anaconda3/lib/python3.9/site-packages/flix_cli/core/__flix_cli__.py", line 219, in <module>
poison()
File "/home/maltesefalcon/anaconda3/lib/python3.9/site-packages/flix_cli/core/__flix_cli__.py", line 213, in poison
movie()
File "/home/maltesefalcon/anaconda3/lib/python3.9/site-packages/flix_cli/core/__flix_cli__.py", line 68, in movie
content_id = CONTENT_ID_REGEX.search(
AttributeError: 'NoneType' object has no attribute 'group'
`

**Comment by DemonKingSwarn** [comment]
dont worry, i would be changing the entire site

**Comment by hexxt-git** [comment]
arch linux
```bash
[hexxt@archlinux flix-cli]$ flix-cli
Search: greenbook
1
Traceback (most recent call last):
  File "/home/hexxt/Downloads/flix-cli/venv/bin/flix-cli", line 5, in <module>
    from flix_cli.__main__ import __flixcli__
  File "/home/hexxt/Downloads/flix-cli/venv/lib/python3.12/site-packages/flix_cli/__main__.py", line 1, in <module>
    from .core import __flix_cli__
  File "/home/hexxt/Downloads/flix-cli/venv/lib/python3.12/site-packages/flix_cli/core/__flix_cli__.py", line 219, in <module>
    poison()
  File "/home/hexxt/Downloads/flix-cli/venv/lib/python3.12/site-packages/flix_cli/core/__flix_cli__.py", line 213, in poison
    movie()
  File "/home/hexxt/Downloads/flix-cli/venv/lib/python3.12/site-packages/flix_cli/core/__flix_cli__.py", line 75, in movie
    ).group(1)
      ^^^^^
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by txvmkkfknv** [comment]
Same error...
AttributeError: 'NoneType' object has no attribute 'group'
