### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by rbjnazz** [DemonKingSwarn/flix-cli#8]
```
➜  flix-cli
Search: baby driver
[*]Results:


1. Baby Driver
2. Baby Driver 2
3. Baby Drivers
4. Ploua Mr. Yash (Baby Driver)
5. Lone Wolf and Cub: Baby Cart at the River Styx
6. Drive Baby Drive
7. Cry Baby River
8. Shrimaan Driver Babu


[*]Enter number: 2

Choose your poison!!!
[m] movie
[s] series
[q] quit
: m
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/flix-cli", line 5, in <module>
    from flix_cli.__main__ import __flixcli__
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/flix_cli/__main__.py", line 1, in <module>
    from .core import __flix_cli__
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/flix_cli/core/__flix_cli__.py", line 212, in <module>
    poison()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/flix_cli/core/__flix_cli__.py", line 206, in poison
    movie()
  File "/data/data/com.termux/files/usr/lib/python3.10/site-packages/flix_cli/core/__flix_cli__.py", line 71, in movie
    ).group(1)
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by DemonKingSwarn** [comment]
It should work now, the api was changed. Fixed it.
