### ISSUE TITLE
flix-cli request/response error (i'm not sure); help!!!

### ISSUE THREAD

**Issue by bachig26** [DemonKingSwarn/flix-cli#9]
**Metadata (please complete the following information)**
Version: 1.5.1
OS: Windows 10
Movie: Castle (TV Series

**Describe the bug**
stream/download (flix-cli) is broken.

**Steps To Reproduce**

@DemonKingSwarn steps and the errors are provided below.

**Expected behavior**
stream/download (flix-cli) should work

**Additional context**

```
flix-cli
Search: castle
[*]Results:


1. Castle
2. A Castle for Christmas
3. Castle Rock
4. The Man in the High Castle
5. Keisha Castle-Hughes
6. Howl's Moving Castle
7. Castle in the Sky
8. Peggie Castle


[*]Enter number: 1

Choose your poison!!!
[m] movie
[s] series
[q] quit
: s
Enter season: 4
Enter episode: 6
Traceback (most recent call last):
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\Scripts\flix-cli.exe\__main__.py", line 4, in <module>
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\flix_cli\__main__.py", line 1, in <module>
    from .core import __flix_cli__
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\flix_cli\core\__flix_cli__.py", line 214, in <module>
    poison()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\flix_cli\core\__flix_cli__.py", line 210, in poison
    series()
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\site-packages\flix_cli\core\__flix_cli__.py", line 133, in series
    json.loads(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by bachig26** [comment]
@DemonKingSwarn possible api issue

**Comment by DemonKingSwarn** [comment]
I will look into it

**Comment by bachig26** [comment]
> I will look into it

thanks

**Comment by cethamine** [comment]
The answer is quite simple, they changed their domain.

So instead of `membed.net`, they changed it to `membed1.com`.

So changing both `ENCRYPT_AJAX_ENDPOINT` & `DEFAULT_MEDIA_REFERER` (in __flix_cli.py) to include the newer domain, it should work.

Edit: They also changed DOT com to DOT net.

**Comment by bachig26** [comment]
> The answer is quite simple, they changed their domain.
> 
> So instead of `membed.net`, they changed it to `membed1.com`.
> 
> So changing both `ENCRYPT_AJAX_ENDPOINT` & `DEFAULT_MEDIA_REFERER` (in __flix_cli.py) to include the newer domain, it should work.
> 
> Edit: They also changed DOT com to DOT net.

thanks, It works and i have also added a PR for it.
